### ISSUE TITLE
refactor: move bot direct hardware control over to DeepHorOpMode

### ISSUE THREAD

**Issue by Preloading** [Bev-Facey-Robotics/BFH15254Repo#10]
For easy implementation of initializtion, auto & manual control, we can move all hardware initialization, movement commands (drive, arm, slide, swing) to an abstract class that we can refrence. 

This lets us

- Easy hardware porting across autos & teleops
- Practicing DRY
- Easy Initalization
- And more!

**Comment by ream900** [comment]
My phone was being dumb and marked it as complete

**Comment by Preloading** [comment]
i already did this then forgot about the issue
