### ISSUE TITLE
Talk to Hay about Dualsense Controllers

### ISSUE THREAD

**Issue by IAmZeMuffinMan** [Bev-Facey-Robotics/BFH15254Repo#9]
See if we can talk Hay into giving us his dualsense controllers for Preloading

**Comment by Preloading** [comment]
Adding on to this, I feel that it would be beneficial for:

- A quick status on the controller via the LED
- Vibration to let know if something has gone wrong
- Moar buttons
- i'm out of ideas help
-

**Comment by misterhay** [comment]
You can certainly use my Dualsense controllers, remind me on Monday.

That would also allow for a Bluetooth connection with the Driver Hub device.

**Comment by IAmZeMuffinMan** [comment]
Dualsense controllers are at school, Preloading can use them now when he's at school next.
